config/routes.rb
Rails.application.routes.draw do
  resources :records
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "/admin", to: "admin#login"
  # Defines the root path route ("/")
  root "records#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/record.rb
class Record < ApplicationRecord
  has_one_attached :image
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  allow_unauthenticated_access
  def login
    # Renders the login view (app/views/admin/login.html.erb)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        Rails.logger.info ">>>Created new session with id: #{Current.session.id}"

        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
        Rails.logger.info ">>>Stored custom session key: #{cookies.signed.permanent[:session_id]}"
        Rails.logger.info ">>> Set cookies for session #{session.id}"
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  allow_unauthenticated_access only: [ :index, :show ]
  before_action :set_record, only: %i[ show edit update destroy ]

  # GET /records or /records.json
  def index
    if params[:query].present?
      query = "%#{params[:query]}%"
      @records = Record.where("title LIKE ? OR artist LIKE ?", query, query)
    else
      @records = Record.order(created_at: :desc)
    end
  end

  # GET /records/1 or /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records or /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: "Record was successfully created." }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1 or /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: "Record was successfully updated." }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1 or /records/1.json
  def destroy
    @record.destroy!

    respond_to do |format|
      format.html { redirect_to records_path, status: :see_other, notice: "Record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def record_params
      params.require(:record).permit(:title, :artist, :description, :youtube_url, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/admin/login.html.erb
<h2>Admin Sign In</h2>

<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

<%= form_with url: session_path do |form| %>
  <%= form.email_field :email_address, required: true, autofocus: true, autocomplete: "username", placeholder: "Enter your email address", value: params[:email_address] %><br>
  <%= form.password_field :password, required: true, autocomplete: "current-password", placeholder: "Enter your password", maxlength: 72 %><br>
  <%= form.submit "Sign in" %>
<% end %>
<br>

<%= link_to "Forgot password?", new_password_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Nineteenseventyeight" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<header style="position: sticky; top: 0; background: white; display: flex; align-items: center; padding: 10px 20px;">
  <!-- Left: Search bar (only if signed in) -->
  <div style="flex: 1; text-align: left;">
    <% if Current.user %>
      <%= form_with url: records_path, method: :get, local: true do |f| %>
        <%= f.text_field :query, placeholder: "Search...", value: params[:query] %>
        <%= f.submit "Search" %>
      <% end %>
    <% end %>
  </div>

  <!-- Center: Title -->
  <div style="flex: 1; text-align: center;">
    <%= link_to root_path, style: "text-decoration: none; color: inherit;" do %>
      <h1 style="margin: 0;">1978</h1>
    <% end %>
  </div>

  <!-- Right: Logout button (only if signed in) -->
  <div style="flex: 1; text-align: right;">
    <% if Current.user %>
      <%= button_to "Logout", session_path, method: :delete, form: { style: "display: inline;" } %>
    <% end %>
  </div>
</header>
<%= yield %>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_with(model: record) do |form| %>
  <% if record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :artist, style: "display: block" %>
    <%= form.text_field :artist %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
  <%= form.label :youtube_url, style: "display: block" %>
  <%= form.text_field :youtube_url %>
  </div>

  <div class="field">
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/records/_record.html.erb
<div class="record-wrapper">
  <div id="<%= dom_id record %>" class="record-container">
    <div class="record-image">
      <% if record.image.attached? %>
        <%= image_tag record.image.variant(resize_to_fill: [300, 300]) %>
      <% else %>
        <p>No image attached.</p>
      <% end %>
    </div>
    <div class="record-details">
      <p><%= record.title %></p>
      <p><%= record.artist %></p>
      <p><%= record.description %></p>
      <% url = record.youtube_url %>
      <% url = "https://#{url}" unless url =~ /\Ahttp(s)?:\/\// %>
      <%= link_to "Click", url, target: "_blank", rel: "noopener noreferrer" %>
    </div>
  </div>
</div>

<style>
.record-wrapper {
  margin-bottom: 25px;
}
/* Make the container shrink-wrap its content (the record image),
   so that the text below aligns with the image's left edge */
.record-container {
  display: inline-block;
  text-align: left;
  margin-bottom: 5px;
}

.record-details {
  margin-top: 5px;
}
p {
  margin-top: 0.2em;  /* Adjust as needed */
  margin-bottom: 0.2em; /* Adjust as needed */
}
</style>

app/views/records/edit.html.erb
<% content_for :title, "Editing record" %>

<h1>Editing record</h1>

<%= render "form", record: @record %>

<br>

<div>
  <%= link_to "Show this record", @record %> |
  <%= link_to "Back to records", records_path %>
</div>

app/views/records/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Records" %>

<div id="records">
<% if authenticated? %>
<div>
  <%= link_to "Add new record", new_record_path %>
</div>
<% end %>  
  <% @records.each do |record| %>
    <% if authenticated? %>
      <%= link_to "Edit this record", record %>
    <% end %>
    <%= render record %>
  <% end %>
</div>

app/views/records/new.html.erb
<% content_for :title, "New record" %>

<h1>New record</h1>

<%= render "form", record: @record %>

<br>

<div>
  <%= link_to "Back to records", records_path %>
</div>

app/views/records/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @record %>

<div>
  <%= link_to "Edit this record", edit_record_path(@record) %> |
  <%= link_to "Back to records", records_path %>

  <%= button_to "Destroy this record", @record, method: :delete %>
</div>